language: node_js
node_js:
- '8'
cache:
- yarn
notifications:
  email: false
script:
- yarn clean
- yarn install
- yarn build:prod
after_success:
- bash ./tasks/deploy.sh
after_failure:
- bash ./tasks/failed.sh
env:
  global:
  - GH_USER: TrondheimDeveloperConference
  - GH_REPO_PROD: trondheimdc-2019-prod
  - GH_REPO_TEST: trondheimdc-2019-test
  - secure: 038de7b8ac42db5b86bf0e706a48de403e1204d9
